### ISSUE TITLE
全部api进行promise封装

### ISSUE THREAD

**Issue by he5050** [skyvow/wx-extend#1]
个人觉得,您可以把所有的方法都进行promse封装,然后里面的api统一使用wxService.api来调用

**Comment by skyvow** [comment]
使用 Promise 是为了解决多层异步调用的回调地狱问题，现已把所有异步都封装了，同步的不做处理。

**Comment by he5050** [comment]
好的，我以为把所的方法都进行了封装,谢谢

**Comment by zisheng-ai** [comment]
@he5050 可以了解下 https://github.com/youngjuning/wxPromise ， 优雅地实现了将所有异步API promise 化，不但支持 then和catch，更支持 ES2018 特性 finally，除此之外也支持了 async、await..... 喜欢的话给个星星
