### ISSUE TITLE
在wepy 中验证表单数据报错

### ISSUE THREAD

**Issue by zhangjiahao93** [skyvow/wx-extend#8]
![image](https://user-images.githubusercontent.com/17284947/42296671-3e6ae072-802b-11e8-9347-a4a34e59d542.png)

我暂时也没找到哪里出错了，正常微信使用Ok，这个不知道是wepy的问题还是 WxValidate 的问题

**Comment by zhangjiahao93** [comment]
跟一句 ，功能是可以使用的 就是有报错。。

**Comment by skyvow** [comment]
@zhangjiahao93 循环引用

**Comment by qqqdu** [comment]
@zhangjiahao93 请问你的问题解决了吗，wepy同样碰到这个问题

**Comment by qqqdu** [comment]
最后解决了这个问题，虽然还没找到原因，不过wepy里面是会有这个报错的。
![image](https://user-images.githubusercontent.com/19419834/42858811-0d0f9c7c-8a83-11e8-8f74-2c23a79499dc.png)
如果传入的是ele节点，就会报错（蜜汁报错），这里用个空对象把detail属性传入就没问题了。

**Comment by skyvow** [comment]
优化了一下 checkForm 可传入自定义对象，不在是 form 返回的参数对象 e
